import image from "../assets/images/image-1.jpg";

const gifts = [
    {
        id: 501,
        name: "a 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 502,
        name: "b 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 503,
        name: "c 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 504,
        name: "d 1",
        url: image,
        price: 999,
        quantity: 0,
    },
    {
        id: 505,
        name: "e 1",
        url: image,
        price: 1299,
        quantity: 0,
    },
    {
        id: 506,
        name: "f 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 507,
        name: "g 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 508,
        name: "h 1",
        url: image,
        price: 999,
        quantity: 0,
    },
    {
        id: 509,
        name: "i 1",
        url: image,
        price: 999,
        quantity: 0,
    },
    {
        id: 510,
        name: "j 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 511,
        name: "k 1",
        url: image,
        price: 999,
        quantity: 0,
    },
    {
        id: 512,
        name: "l 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 513,
        name: "m 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 514,
        name: "n 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 515,
        name: "o 1",
        url: image,
        price: 799,
        quantity: 0,
    },
    {
        id: 516,
        name: "p 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 517,
        name: "gift 1",
        url: image,
        price: 999,
        quantity: 0,
    },
    {
        id: 518,
        name: "gift 1",
        url: image,
        price: 899,
        quantity: 0,
    },
    {
        id: 519,
        name: "gift 1",
        url: image,
        price: 1999,
        quantity: 0,
    },
    {
        id: 520,
        name: "gift 1",
        url: image,
        price: 1299,
        quantity: 0,
    },
    {
        id: 521,
        name: "gift 1",
        url: image,
        price: 1099,
        quantity: 0,
    },
];

export default gifts;
